/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Auto-generated by SentencePiece Lite Amalgamation Tool (C++20).
// DO NOT EDIT DIRECTLY.

namespace linpipe {
#ifndef SENTENCEPIECE_LITE_AMALGAMATED_H_
#define SENTENCEPIECE_LITE_AMALGAMATED_H_

} // namespace linpipe
#include <algorithm>
#include <array>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <functional>
#include <memory>
#include <string>
#include <string_view>
#include <vector>

// === Public Interface ===


// The SentencePiece Lite Runtime is a lightweight, dependency-free C++ library
// that executes tokenization directly on FlatBuffers model binaries (.spm.fb).
// It supports Unigram and BPE tokenization, byte fallback, and full text
// normalization.
//
// Key Design Highlights:
// * Zero Dependencies: Depends only on FlatBuffers and standard C++20.
// * Zero-Copy Startup: Maps and reads model vocabulary, scores, and tries in
//   place without heap allocation or parsing overhead.
// * Stateless & Thread-Safe: The processor instance is read-only after
//   initialization, making it fully thread-safe across concurrent threads.
// * Minimalist Integer API: High-performance text encoding/decoding operating
//   directly on string views and integer token vectors.
//
// Development & Contributing Rules:
// 1. Minimalism Design: Focus on core functionality required for tokenization.
//    Avoid introducing fancy or non-essential features (e.g., operations that
//    can be implemented purely in post-processing or pre-processing outside
//    this runtime).
// 2. Zero External Dependencies: Do not introduce extra dependencies such as
//    Abseil or Protobuf.
// 3. Minimal Initialization Allocation: Minimize heap allocations during model
//    initialization (avoid allocating large containers like std::vector or
//    std::map).
// 4. Performance Verification: Always run performance benchmarks to ensure no
//    regressions are introduced.
// 5. Simplicity & Cleanliness: Avoid over-engineering, and keep the codebase
//    clean, concise, and simple.


namespace linpipe {
#ifdef SENTENCEPIECE_LITE_USE_ABSL
#endif

namespace sentencepiece::lite {

// StatusCode is a lightweight replacement for absl::StatusCode.
// The underlying integer values are identical to the corresponding values
// in absl::StatusCode.
// To convert a StatusCode `code` to absl::Status, you can use:
//   absl::Status(static_cast<absl::StatusCode>(code), "error message");
enum class StatusCode : int {
  kOk = 0,
  kInvalidArgument = 3,
  kFailedPrecondition = 9,
  kInternal = 13,
};

#ifdef SENTENCEPIECE_LITE_USE_ABSL
template <typename T>
using Span = absl::Span<T>;

template <typename Signature>
using FunctionRef = absl::FunctionRef<Signature>;
#else
// A lightweight, zero-dependency implementation of a span.
// We avoid absl::Span and std::span to keep the public API of this "lite"
// library completely dependency-free across C++ standards.
template <typename T>
class Span {
 public:
  Span() = default;
  Span(T* data, size_t size) : data_(data), size_(size) {}

  template <size_t N>
  Span(T (&array)[N])  // NOLINT(google-explicit-constructor)
      : data_(array), size_(N) {}

  template <typename Container,
            typename = decltype(std::declval<Container&>().data())>
  Span(Container& c)  // NOLINT(google-explicit-constructor)
      : data_(c.data()), size_(c.size()) {}

  template <typename Container,
            typename = decltype(std::declval<const Container&>().data())>
  Span(const Container& c)  // NOLINT(google-explicit-constructor)
      : data_(c.data()), size_(c.size()) {}

  template <typename Container,
            typename = decltype(std::declval<const Container&>().data())>
  Span(const Container&& c) = delete;

  T* data() const { return data_; }
  size_t size() const { return size_; }
  bool empty() const { return size_ == 0; }

  T* begin() const { return data_; }
  T* end() const { return data_ + size_; }

  T& operator[](size_t i) const { return data_[i]; }

 private:
  T* data_ = nullptr;
  size_t size_ = 0;
};

// A lightweight, zero-dependency, non-owning function reference for C++17.
// Replaces std::function and absl::FunctionRef without heap allocation.
template <typename Signature>
class FunctionRef;

template <typename ReturnType, typename... Args>
class FunctionRef<ReturnType(Args...)> {
 public:
  template <typename Callable,
            typename = std::enable_if_t<
                !std::is_same_v<std::decay_t<Callable>, FunctionRef> &&
                std::is_invocable_r_v<ReturnType, Callable, Args...> > >
  constexpr FunctionRef(Callable&& callable) noexcept
      : callable_ptr_(reinterpret_cast<intptr_t>(&callable)),
        invoker_([](intptr_t ptr, Args... args) -> ReturnType {
          return (*reinterpret_cast<std::add_pointer_t<Callable> >(ptr))(
              std::forward<Args>(args)...);
        }) {}

  ReturnType operator()(Args... args) const {
    return invoker_(callable_ptr_, std::forward<Args>(args)...);
  }

 private:
  intptr_t callable_ptr_ = 0;
  ReturnType (*invoker_)(intptr_t, Args...) = nullptr;
};
#endif

class Model;

// Main tokenization runtime processor executing Unigram and BPE tokenization
// on FlatBuffers model binaries (.spm.fb).
class SentencePieceLiteProcessor;
using SentencePieceLite = SentencePieceLiteProcessor;

class SentencePieceLiteProcessor {
 public:
  SentencePieceLiteProcessor() = delete;

  // Constructs the processor and loads the model from the memory buffer.
  // Note: The memory buffer must remain valid and outlive this processor
  // instance, as the processor accesses the buffer directly without copying.
  explicit SentencePieceLiteProcessor(std::string_view buffer);

  // Constructs the processor by retaining shared ownership of the model buffer.
  explicit SentencePieceLiteProcessor(
      std::shared_ptr<std::string> shared_buffer);
  ~SentencePieceLiteProcessor();

  // Returns the status of the model loading/initialization.
  StatusCode status() const;

  // Normalizes text using model rules. If not nullptr, `(*offset)[x]` stores
  // the byte index in `input` corresponding to `output[x]` (with a sentinel at
  // `output->size()`).
  StatusCode Normalize(std::string_view input, std::string* output,
                       std::vector<size_t>* offset = nullptr) const;

  // Encode text to token IDs
  StatusCode Encode(std::string_view input, std::vector<int>* ids) const;

  // Encodes normalized text. `pieces` stores string views into `normalized` if
  // not nullptr. Assumes input is already normalized.
  StatusCode EncodeNormalized(
      std::string_view normalized, std::vector<int>* ids,
      std::vector<std::string_view>* pieces = nullptr) const;

  // Encodes a single pre-tokenized, normalized chunk without running
  // `PretokenizeAtSafeBoundaries`. Unlike `EncodeNormalized`, this method
  // skips pre-tokenization and directly encodes the chunk.
  StatusCode EncodeNormalizedChunk(
      std::string_view normalized_chunk, std::vector<int>* ids,
      std::vector<std::string_view>* pieces = nullptr) const;

  // Encodes normalized text using stochastic sampling for data augmentation
  // and subword regularization. When `uniform_sampler` is provided, sampling
  // mode is active across all non-negative `alpha` (>= 0.0) values:
  //
  // - Unigram (--model_type=unigram):
  //   `alpha`: Temperature noise scale controlling the magnitude of Gumbel
  //   perturbations (`score + alpha * Gumbel()`) where each segmentation `S`
  //   is sampled proportional to `P(S)^alpha` (Kudo, 2018,
  //   https://arxiv.org/abs/1804.10959). While the original Kudo (2018) paper
  //   uses Forward-Filtering and Backward-Sampling (FFBS), this lightweight
  //   runtime adopts the simpler Gumbel-Max/Softmax trick during Viterbi
  //   search, yielding theoretically identical stochastic behavior.
  //   * `alpha` == 0.0: Zero noise addition (`score + 0`), returning the best
  //     deterministic Viterbi segmentation.
  //   * `alpha` == 1.0: Corresponds to standard Gibbs posterior sampling
  //     without smoothing or sharpening.
  //   * `alpha` > 0.0: Larger `alpha` yields more diverse subword variations.
  //     Empirically recommended values are around 0.1 to 0.2 (Kudo, 2018).
  //
  // - BPE (--model_type=bpe):
  //   `alpha`: The dropout probability `p` in [0.0, 1.0] of BPE merge
  //   operations (Provilkov et al., 2020, https://arxiv.org/abs/1910.13267).
  //   * `alpha` == 0.0: Zero dropout, returning standard deterministic BPE.
  //   * `alpha` in (0.0, 1.0): Drops merge steps with probability `alpha`.
  //     Empirically recommended values are around 0.1 (Provilkov et al., 2020).
  //   * `alpha` >= 1.0: All merges are dropped, yielding character/base-symbol
  //     segmentation.
  //
  // `alpha` must be non-negative (`alpha` >= 0.0). `uniform_sampler` generates
  // uniform reals in [0.0, 1.0). `pieces` stores string views into `normalized`
  // if not nullptr. Assumes normalized input.
  StatusCode SampleNormalized(
      std::string_view normalized, float alpha,
      FunctionRef<float()> uniform_sampler, std::vector<int>* ids,
      std::vector<std::string_view>* pieces = nullptr) const;

  // Pre-tokenizes normalized text into chunks at safe, non-overlapping boundary
  // points, invoking `receiver` for each chunk with zero heap allocation.
  StatusCode PretokenizeAtSafeBoundaries(
      std::string_view normalized,
      FunctionRef<void(std::string_view)> receiver) const;

  // Convenience overload that collects chunks into a std::vector.
  StatusCode PretokenizeAtSafeBoundaries(
      std::string_view normalized, std::vector<std::string_view>* out) const {
    if (out == nullptr) return StatusCode::kInvalidArgument;
    out->clear();
    return PretokenizeAtSafeBoundaries(
        normalized, [out](std::string_view chunk) { out->push_back(chunk); });
  }

  // Decodes token IDs to text. `pieces` stores string views into `output` if
  // not nullptr.
  StatusCode Decode(Span<const int> ids, std::string* output,
                    std::vector<std::string_view>* pieces = nullptr) const;

  // Returns the ID of the given piece.
  // Returns -1 if the piece is not found or if no model is loaded.
  int PieceToId(std::string_view piece) const;

  // Returns the string piece corresponding to the given ID.
  // Returns "<unk>" if the ID is out of bounds or if no model is loaded.
  std::string_view IdToPiece(int id) const;

  // Returns the score of the given ID.
  // Returns 0.0 if the ID is out of bounds or if no model is loaded.
  float GetScore(int id) const;

  // Returns the unk id of the sentence piece processor.
  // Returns -1 if disabled or undefined.
  int unk_id() const;

  // Returns the bos id of the sentence piece processor.
  // Returns -1 if disabled or undefined.
  int bos_id() const;

  // Returns the eos id of the sentence piece processor.
  // Returns -1 if disabled or undefined.
  int eos_id() const;

  // Returns the pad id of the sentence piece processor.
  // Returns -1 if disabled or undefined.
  int pad_id() const;

  // Returns the size of the vocabulary.
  // Returns 0 if no model is loaded.
  size_t vocab_size() const;

  // Returns the type of the piece corresponding to the given ID.
  // The returned value corresponds to the PieceType enum defined in the
  // FlatBuffers schema:
  // DEFAULT=0, NORMAL=1, UNKNOWN=2, CONTROL=3, USER_DEFINED=4, UNUSED=5, BYTE=6
  // Returns -1 if the ID is out of bounds or if no model is loaded.
  int piece_type(int id) const;

  // For testing/internal usage only.
  bool HasNonNullDirectMappingVectorForTesting() const;
  void SetScoreResetThresholdForTesting(float threshold);

 private:
  std::shared_ptr<std::string> shared_buffer_;
  std::unique_ptr<Model> model_;
  StatusCode status_ = StatusCode::kFailedPrecondition;
};

}  // namespace sentencepiece::lite


// === Cached Tokenizer Interface ===




namespace sentencepiece::lite {

// 2-Way Set-Associative Token Cache for SentencePieceLite.
//
// Features:
// - Zero Heap Allocations during Lookup and Insert.
// - 64B L1 Cache-Line alignment with 2-way short-circuit scalar search.
// - 1-Bit PLRU (Pseudo-LRU) replacement policy.
// - Single-block branchless (CMOV) Insert.
//
// Thread safety: Not thread-safe for concurrent writes. Use per-thread
// instances (e.g. thread_local TokenCache) or caller-managed thread-local
// scope.
class TokenCache {
 public:
  // Maximum number of subword tokens cached per pre-tokenized chunk.
  static constexpr size_t kMaxCachedTokenCount = 5;

  // Computes a 16-bit zero-overhead fingerprint (length + boundary signature)
  // from pre-tokenized chunk.
  static inline uint16_t MakeChunkTag(std::string_view chunk) {
    if (chunk.empty()) return 0;
    const uint8_t len = static_cast<uint8_t>(chunk.size());
    // Bijective mapping on single-char chunks: (c * 2) + c = 3 * c (mod 256).
    // Since gcd(3, 256) == 1, all 256 byte values map 1-to-1 uniquely.
    const uint8_t char_sig =
        static_cast<uint8_t>((static_cast<uint8_t>(chunk.front()) * 2) +
                             static_cast<uint8_t>(chunk.back()));
    return static_cast<uint16_t>((static_cast<uint16_t>(len) << 8) | char_sig);
  }

 private:
  // 32-Byte Aligned Cache Entry.
  struct alignas(32) TokenCacheEntry {
    uint64_t hash = 0;        // 64-bit Hash value
    uint8_t token_count = 0;  // token id count.
    uint8_t mru_bit = 0;      // 1 is MRU (Most Recently Used), 0 is LRU.
    uint16_t tag = 0;         // 16-bit Length & Boundary Fingerprint
    int32_t token_ids[kMaxCachedTokenCount] = {0, 0, 0, 0,
                                               0};  // Cached token ids.
  };
  static_assert(sizeof(TokenCacheEntry) == 32,
                "TokenCacheEntry must be exactly 32 bytes!");
  // 64-Byte Aligned Cache Pair (Fits exactly in 1 CPU L1 Cache Line).
  struct alignas(64) TokenCachePair {
    TokenCacheEntry entries[2];
  };
  static_assert(sizeof(TokenCachePair) == 64,
                "TokenCachePair must be exactly 64 bytes!");

 public:
  // Pre-defined power-of-2 cache capacities.
  //
  // Sizing Guide:
  // - kTiny (64 KB, 2,048 slots): Minimal memory footprint. Recommended for
  //   memory-constrained environments (e.g., mobile or embedded devices).
  // - kSmall (256 KB, 8,192 slots): Low memory footprint. Recommended for
  //   lightweight workers or tight per-thread memory budgets.
  // - kMedium (1 MB, 32,768 slots, Default): Balanced capacity and memory
  //   usage for general server-side serving pipelines.
  // - kLarge (8 MB, 262,144 slots): High capacity for large batch workloads or
  //   diverse multi-domain text.
  enum class Capacity : size_t {
    kTiny = 1024,     // 1,024 pairs = 2,048 slots (64 KB)
    kSmall = 4096,    // 4,096 pairs = 8,192 slots (256 KB)
    kMedium = 16384,  // 16,384 pairs = 32,768 slots (1 MB, Default)
    kLarge = 131072,  // 131,072 pairs = 262,144 slots (8 MB)
  };

  // Initializes TokenCache with default capacity (kMedium, 1 MB) and a dynamic
  // random seed.
  TokenCache();

  // Initializes TokenCache with an explicit capacity and optional seed (0 =
  // dynamic seed).
  explicit TokenCache(Capacity capacity, uint64_t seed = 0);

  // Initializes TokenCache with default capacity (kMedium, 1 MB) and an
  // explicit seed.
  explicit TokenCache(uint64_t seed);

  // Returns the 64-bit random seed associated with this cache instance.
  uint64_t seed() const { return seed_; }

  // Returns the total number of cache slots (2 * num_pairs).
  size_t capacity() const { return num_pairs_ * 2; }
  size_t num_pairs() const { return num_pairs_; }

  // Clear all entries cleanly.
  void Clear() {
    if (!pairs_) {
      pairs_ = std::make_unique<TokenCachePair[]>(num_pairs_);
    }
    std::memset(static_cast<void*>(pairs_.get()), 0,
                sizeof(TokenCachePair) * num_pairs_);
  }

  // Direct 2-Way Short-Circuit Scalar Cache Lookup with 1-Bit PLRU Update and
  // 16-bit Tag Validation.
  const int32_t* Lookup(uint64_t hash, uint16_t tag, size_t* out_count) {
    const size_t pair_idx = (hash & mask_);
    TokenCachePair& pair = pairs_[pair_idx];

    // Short-circuit: hash comparison failure skips tag and token_count checks.
    if (pair.entries[0].hash == hash && pair.entries[0].tag == tag &&
        pair.entries[0].token_count != 0) {
      *out_count = pair.entries[0].token_count;
      pair.entries[0].mru_bit = 1;
      pair.entries[1].mru_bit = 0;
      return pair.entries[0].token_ids;
    }
    if (pair.entries[1].hash == hash && pair.entries[1].tag == tag &&
        pair.entries[1].token_count != 0) {
      *out_count = pair.entries[1].token_count;
      pair.entries[1].mru_bit = 1;
      pair.entries[0].mru_bit = 0;
      return pair.entries[1].token_ids;
    }
    return nullptr;
  }

  // Insert or Update Cache Entry using Single-Block Branchless 1-Bit PLRU.
  void Insert(uint64_t hash, uint16_t tag, const int32_t* ids, size_t count) {
    if (count == 0 || count > kMaxCachedTokenCount) return;

    const size_t pair_idx = (hash & mask_);
    TokenCachePair& pair = pairs_[pair_idx];

    // Check if slot 0 or slot 1 is occupied (token_count != 0)
    const uint8_t occ0 = (pair.entries[0].token_count != 0 ? 1 : 0);
    const uint8_t occ1 = (pair.entries[1].token_count != 0 ? 1 : 0);

    // Check if occupied slot matches existing hash and tag
    const uint8_t match0 =
        (occ0 && pair.entries[0].hash == hash && pair.entries[0].tag == tag
             ? 1
             : 0);
    const uint8_t match1 =
        (occ1 && pair.entries[1].hash == hash && pair.entries[1].tag == tag
             ? 1
             : 0);

    // If both slots occupied, evict Least Recently Used (mru_bit == 0) slot.
    // If slot 0 is MRU (mru_bit == 1), evict slot 1. Else evict slot 0.
    const uint8_t plru_evict = (pair.entries[0].mru_bit == 1 ? 1 : 0);
    const uint8_t fallback_slot = (occ0 & occ1) ? plru_evict : occ0;

    // Single unified target_slot determination (Branchless CMOV):
    // Match 0 -> Slot 0, Match 1 -> Slot 1, Else -> Empty or PLRU Slot
    const uint8_t target_slot = match0 ? 0 : (match1 ? 1 : fallback_slot);

    TokenCacheEntry& target = pair.entries[target_slot];
    TokenCacheEntry& sibling = pair.entries[target_slot ^ 1];
    target.hash = hash;
    target.tag = tag;
    target.token_count = static_cast<uint8_t>(count);
    target.mru_bit = 1;
    sibling.mru_bit = 0;
    for (size_t i = 0; i < count; ++i) {
      target.token_ids[i] = ids[i];
    }
  }

 private:
  size_t num_pairs_ = static_cast<size_t>(Capacity::kMedium);
  size_t mask_ = static_cast<size_t>(Capacity::kMedium) - 1;
  uint64_t seed_ = 0;
  std::unique_ptr<TokenCachePair[]> pairs_;
};

// High-level Utility Class for Cached SentencePieceLite Tokenization.
//
// Cache Key Partitioning and Multi-Model Thread-Local Usage:
//   CachedSentencePieceLite mixes the memory address of the `processor`
//   instance into the effective hashing seed (`cache.seed() ^
//   (uintptr_t)&processor * kGoldenRatio`). This allows a single shared
//   `thread_local TokenCache` to safely tokenize requests across different
//   `SentencePieceLiteProcessor` instances without cross-model cache collisions
//   or output corruption (pseudo per-instance cache partitioning).
//
//   CAVEAT ON CACHE UTILIZATION:
//   While functionally safe and collision-free, if multiple distinct model
//   instances frequently interleave tokenization on the same shared
//   thread-local cache, cache lines will experience increased PLRU eviction,
//   reducing overall cache hit rate and utilization. For maximum throughput in
//   multi-model serving pipelines, dedicated per-processor cache instances are
//   recommended.
//
// Example usage:
//   // Initialize processor once (thread-safe, read-only across threads)
//   SentencePieceLiteProcessor processor(model_buffer);
//
//   // Worker function executed across worker threads
//   void TokenizeWorker(const SentencePieceLiteProcessor& processor,
//                       std::string_view text) {
//     // Thread-local cache instance
//     static thread_local TokenCache cache;
//
//     std::vector<int> ids;
//     StatusCode status =
//         CachedSentencePieceLite::Encode(processor, cache, text, &ids);
//     if (status == StatusCode::kOk) {
//       // Process token IDs...
//     }
//   }
class CachedSentencePieceLite {
 public:
  // Encodes raw `text` into token `ids` using `processor` and accelerating
  // repeated pre-tokenized chunks via `cache`. Automatically performs text
  // normalization.
  //
  // Returns StatusCode::kOk on success, or an error status code on failure.
  //
  // Thread safety: Thread-safe if each thread uses its own `TokenCache`
  // instance (e.g. thread_local TokenCache).
  static StatusCode Encode(const SentencePieceLiteProcessor& processor,
                           TokenCache& cache, std::string_view text,
                           std::vector<int>* ids);

  // Encodes pre-normalized `normalized_text` into token `ids` using `processor`
  // and accelerating repeated pre-tokenized chunks via `cache`.
  // Skips the text normalization step for maximum performance when the input is
  // already normalized.
  //
  // Returns StatusCode::kOk on success, or an error status code on failure.
  //
  // Thread safety: Thread-safe if each thread uses its own `TokenCache`
  // instance (e.g. thread_local TokenCache).
  static StatusCode EncodeNormalized(
      const SentencePieceLiteProcessor& processor, TokenCache& cache,
      std::string_view normalized_text, std::vector<int>* ids);
};

}  // namespace sentencepiece::lite


#endif  // SENTENCEPIECE_LITE_AMALGAMATED_H_

} // namespace linpipe
