[project]
site_name = "LinPipe:  Multilingual Processing Tool"
site_url = "https://linpipe.org/"
repo_url = "https://github.com/ufal/linpipe"
docs_dir = "src"
site_dir = "site"

nav = [
  { "LinPipe" = [
    "index.md",
    "design.md",
  ] },
  { "Get Started" = [
    "get_started/installation.md",
    { "Tutorials" = [
      { "Tutorial1" = "..." }, { "Tutorial2" = "..." }, { "Tutorial3" = "..." },
    ] },
  ] },
  { "Models" = [
    "models/index.md",
    { "Tokenization" = [
      { "Model1" = "..." }, { "Model2" = "..." }, { "Model3" = "..." },
    ] },
    { "Morphosyntactic Analysis" = [
      { "Model1" = "..." }, { "Model2" = "..." }, { "Model3" = "..." },
    ] },
    { "Named Entity Recognition" = [
      { "Model1" = "..." }, { "Model2" = "..." }, { "Model3" = "..." },
    ] },
    { "Privacy Filtering" = [
      { "Model1" = "..." }, { "Model2" = "..." }, { "Model3" = "..." },
    ] },
    { "Coreference Resolution" = [
      { "Model1" = "..." }, { "Model2" = "..." }, { "Model3" = "..." },
    ] },
    { "Semantic Analysis" = [
      { "Model1" = "..." }, { "Model2" = "..." }, { "Model3" = "..." },
    ] },
  ] },
  { "Training" = [
    "training/index.md",
    { "Tokenization" = [
      { "Model1" = "..." }, { "Model2" = "..." }, { "Model3" = "..." },
    ] },
    { "Morphosyntactic Analysis" = [
      { "Model1" = "..." }, { "Model2" = "..." }, { "Model3" = "..." },
    ] },
    { "Named Entity Recognition" = [
      { "Model1" = "..." }, { "Model2" = "..." }, { "Model3" = "..." },
    ] },
    { "Privacy Filtering" = [
      { "Model1" = "..." }, { "Model2" = "..." }, { "Model3" = "..." },
    ] },
    { "Coreference Resolution" = [
      { "Model1" = "..." }, { "Model2" = "..." }, { "Model3" = "..." },
    ] },
    { "Semantic Analysis" = [
      { "Model1" = "..." }, { "Model2" = "..." }, { "Model3" = "..." },
    ] },
  ] },
  { "API Reference" = [
    "api_reference.md",
  ] },
  { "Development" = [
    {"System Architecture" = [
      { "Overview" = "dev/architecture.md" }, {"Segmentation and Tokenization" = "dev/segmentation_tokenization.md" }
    ] },
    "dev/codestyle.md",
    "dev/commandline.md",
    "dev/notes.md",
  ] },
]

extra_css = [
  "https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css",
  "assets/extra.css",
]
extra_javascript = [
  "https://cdn.jsdelivr.net/npm/katex/dist/katex.min.js",
  "assets/katex_load.js",
]

[project.theme]
logo = "images/favicon.svg"
favicon = "images/favicon.svg"
font.text = "Inter"
font.code = "JetBrains Mono"
features = [
  "content.code.copy",
  "navigation.tabs",
  "navigation.tabs.sticky",
  "navigation.top",
  "search.highlight",
  "toc.follow",
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "indigo"
accent = "blue"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "indigo"
accent = "orange"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.extra]
generator = false

[project.markdown_extensions]
attr_list = {}
md_in_html = {}
pymdownx.arithmatex.generic = true
pymdownx.arithmatex.inline_syntax = ["dollar"]
pymdownx.arithmatex.block_syntax = ["dollar"]
pymdownx.highlight = {}
pymdownx.inlinehilite = {}
pymdownx.snippets.base_path = ["."]
pymdownx.snippets.check_paths = true
pymdownx.superfences.custom_fences = [ { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" } ]
pymdownx.tabbed.alternate_style = true
pymdownx.tabbed.slugify.kwds.case = "lower"

[project.plugins.markdown-exec]
