# This file is part of LinPipe <http://github.com/ufal/linpipe/>.
#
# Copyright 2022-2023 Institute of Formal and Applied Linguistics, Faculty
# of Mathematics and Physics, Charles University in Prague, Czech Republic.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

$(call exe,dev/kbelik/kbelik): $(call obj,dev/kbelik/kbelik dev/kbelik/typed_value $(LINPIPE_OBJECTS) utils/win_wmain_utf8)
	$(call link_exe,$@,$^,$(call win_subsystem,console,wmain))

.PHONY: dev/kbelik
dev/kbelik: $(call exe,dev/kbelik/kbelik)
dev: dev/kbelik

EXECUTABLES += dev/kbelik/kbelik

LINPIPE_TESTS += dev/kbelik/agnostic_entity_info
LINPIPE_TESTS += dev/kbelik/agnostic_kbelik
LINPIPE_TESTS += dev/kbelik/huffman
LINPIPE_TESTS += dev/kbelik/id
LINPIPE_TESTS += dev/kbelik/specific_entity_info
LINPIPE_TESTS += dev/kbelik/typed_value
LINPIPE_TESTS += dev/kbelik/utils

LINPIPE_TESTS += dev/kbelik/kbelik_test
